num=int(input("Type one number"))
num2=int(input("Type another number"))
print(num+num2)
numsub=int(input("Type a number"))
numsub2=int(input("Type another number"))
print(numsub-numsub2)
nummult=int(input("Type one number"))
nummult2=int(input("Type another number"))
print(nummult*nummult2)